# Jekyll Configuration File
# Hayfever for Chrome Website
#
# http://mikedamage.github.com/hayfever-chrome

destination: /Users/mike/ProjectFiles/Hayfever/site
auto: false
lsi: false
pygments: true
#permalink: /hayfever-chrome/:year/:month/:day/:title.html
permalink: pretty
